name = "Tella"
license = "MIT"
licenselink = "https://github.com/Kempner-FD/hugo-tella/blob/master/LICENSE"
description = "Simple, Light, Responsive"

homepage = "https://github.com/Kempner-FD/hugo-tella"
demosite = "https://tella.pages.dev"

tags = ["light", "simple", "blog", "clean", "tailwindcss", "responsive", "company", "modern", "slide"]
features = ["blog", "slides", "responsive"]

[author]
  name = "wamo"
  homepage = "https://wmsci.com"
